### ISSUE TITLE
可以解决draft目录下文章分类问题吗

### ISSUE THREAD

**Issue by zq-97** [zthxxx/hexo-directory-category#3]
如题，`source/_draft`下的文章`foo/bar.md`会被归类为`.. -> _draft -> foo`，因该是使用不区分地相对路径导致的，能优化吗。

**Comment by zthxxx** [comment]
可是， `_draft`  下的文章应该根本不会被渲染呀，

并且配置中 `force: false` 时，手动设置 `categories` 是会覆盖路径判断的；

能不能晒出下你的具体配置代码以及项目结构

**Comment by zq-97** [comment]
@zthxxx 
如果`hexo g/ hexo s`加上`--draft`选项是会渲染草稿的。
```
.
├── _drafts
│   └── 计算模型导引
│       └── 1-递归函数.md
└── _posts
    └── 这些
        └── 都正常.md

```
下面是结果
![image](https://user-images.githubusercontent.com/17429111/54085418-e2b28e80-4378-11e9-9313-625a1bdb38d6.png)
不过老实说，正常编辑完成进行发布肯定不会出现这种问题，毕竟也只有正在编辑中的文章才会放在`_draft`目录下。权当无关痛痒的一个小bug吧。

**Comment by zthxxx** [comment]
手动设置 `categories` 可以临时解决你的需求么？

https://github.com/zthxxx/hexo-directory-category#1-enable-true-force-false

----------

hexo 后面更新过好几版了，我都忘了 drafts 的路径是怎么识别的了

不过大概是 [这个文件这里](https://github.com/zthxxx/hexo-directory-category/blob/master/lib/classify.js#L7) 

需要加一样判断前两个目录是不是 ../_drafts

**Comment by zq-97** [comment]
手动设置没问题的。
不过强迫症还是改了下源码发现可修复这个问题，已经提交了PR

**Comment by zq-97** [comment]
PR似乎复杂度超标了，看来我还是自己改着用着就行了吧

**Comment by zthxxx** [comment]
closed by #4
