### ISSUE TITLE
插件无效果？

### ISSUE THREAD

**Issue by mylovesaber** [zthxxx/hexo-directory-category#6]
主题是：https://github.com/blinkfox/hexo-theme-matery
最新版hexo，
安装步骤：
1. 安装插件后，
2. 在_post目录新建一个PT文件夹，通过hexo n abc新建了一个abc.md文件并移动到PT这个文件夹内
3. 网站根目录的_config.yml按照设置两个都是true
4. scaffolds/post.md信息如下：
```
---
title: {{ title }}
date: {{ date }}
tags: 
category:
comments: true
updated: {{ updated }}
top: true
cover: false
coverImg: 
author: 
img: 
mathjax: false
---
```
最开始post.md有category这一行，自动生成的abc.md也有那一行，但默认冒号后什么都没写，hexo clean && hexo g之后，打开abc.md没有发现category:有任何变化，abc.md和post.md都删掉category:之后再hexo g，依旧无效，没有添加进任何信息？是我哪里理解错误了吗？

**Comment by zthxxx** [comment]
![image](https://user-images.githubusercontent.com/15135943/59156257-80c60a00-8aca-11e9-8d97-b7adfd9d93b7.png)

插件是运行时把 `categories` 属性加进 hexo 的，不会改变源码
